export const paragraphs = [
  "The quick brown fox jumps over the lazy dog near the river bank.",
  "Technology has changed the way we communicate with each other every single day.",
  "Learning to type faster takes practice, patience, and daily dedication.",
  "The sun rises in the east and sets in the west each and every day.",
  "Reading books is one of the best ways to improve your vocabulary and writing.",
  "A good programmer writes code that is clean, readable, and well documented.",
  "The mountains were covered in snow as far as the eye could see.",
  "She opened the door slowly and stepped into the dimly lit hallway.",
  "Science and technology have transformed modern life in countless remarkable ways.",
  "The old clock on the wall ticked softly through the quiet night.",
  "Music has the power to change your mood in just a few seconds.",
  "He typed quickly on the keyboard while looking at the bright screen.",
  "The forest was full of tall trees and the sound of birds singing.",
  "Coding is like solving puzzles — each problem has a creative solution.",
  "A healthy diet and regular exercise are key to a long happy life.",
  "The train arrived at the station exactly on time without any delays.",
  "Writing every day helps you express your thoughts more clearly and confidently.",
  "The little cat sat on the warm windowsill watching the rain outside.",
  "Space exploration is one of humanity's greatest adventures and achievements.",
  "She laughed at the funny story her friend shared over lunch today.",
  "The city lights glittered like stars against the dark evening sky.",
  "Building great software requires clear thinking, teamwork, and strong communication.",
  "He walked through the park every morning to clear his mind and relax.",
  "The chef prepared a delicious meal using only fresh local ingredients.",
  "Children learn best when they are curious, engaged, and having fun.",
  "The waves crashed gently against the shore as the tide came in.",
  "Every great journey begins with a single step in the right direction.",
  "The library was filled with thousands of books waiting to be explored.",
  "She solved the math problem quickly and moved on to the next one.",
  "The world is full of interesting people with unique stories to share.",
  "Innovation drives progress and opens doors to new possibilities every day.",
  "He packed his bag carefully before heading out on the long hike.",
  "The stars were especially bright on that clear and cold winter night.",
  "Kindness costs nothing but means everything to those who receive it.",
  "The bicycle leaned against the old stone wall outside the bakery.",
  "She finished the report just before the deadline with seconds to spare.",
  "The river flowed quietly through the valley between two green hills.",
  "Good habits practiced consistently lead to extraordinary long-term results.",
  "The puppy wagged its tail happily when it saw its owner coming home.",
  "A warm cup of tea is the perfect companion on a rainy afternoon.",
  "The photographer captured the perfect moment just as the sun was setting.",
  "He had always dreamed of visiting the ancient ruins of Rome.",
  "The students worked together on their project late into the evening.",
  "Digital tools have made it easier than ever to learn new skills online.",
  "The baker pulled fresh loaves of bread out of the oven every morning.",
  "She smiled when she read the kind note left on her desk.",
  "The road wound through pine forests and over wooden bridges.",
  "Persistence is the most important trait shared by all successful people.",
  "The telescope revealed thousands of galaxies hidden in the dark night sky.",
  "He finished his coffee and opened his laptop to begin the day.",
];
